### ISSUE TITLE
Add --no-color option for CI

### ISSUE THREAD

**Issue by ElijahLynn** [provision-ops/yaml-tests#16]
Would be nice to have a `--no-color` option for CI purposes where you are not running command locally, and have output in Jenkins for instance.

**Comment by jonpugh** [comment]
It's a Symfony/composer command so I'm pretty sure it's built in:  

```sh
$ composer yaml-tests --help
      --ansi                       Force ANSI output
      --no-ansi                    Disable ANSI output
```

As for the tests, that's on the test writers to figure out. Maybe we need to pass whatever --ansi is to the process as an environment variable so users could check it in their tests?

**Comment by jonpugh** [comment]
Please feel free to open a new issue if there's a more specific idea here.

**Comment by ElijahLynn** [comment]
Thanks!
